# CircleCI Pre-Built Docker Images
# - https://circleci.com/docs/2.0/circleci-images/

# CirlceCI Configuration
version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.3

# References
references:

  working_directory: &working_directory
    ~/app

  image_node: &image_node
    image: cimg/node:18

  image_node_browsers: &image_node_browsers
    image: cimg/node:18-browsers

  job_defaults: &job_defaults
    working_directory: *working_directory
    docker:
      - *image_node

  job_defaults_browsers: &job_defaults_browsers
    working_directory: *working_directory
    docker:
      - *image_node_browsers

  restore_yarn_cache: &restore_yarn_cache
    restore_cache:
      key: dependency-cache-{{ checksum "yarn.lock" }}

  restore_yarn_cache_peer: &restore_yarn_cache_peer
    restore_cache:
      key: dependency-cache-peer-{{ checksum "yarn.lock" }}

# Jobs
jobs:
  build:
    <<: *job_defaults
    steps:
      - checkout
      - *restore_yarn_cache
      - *restore_yarn_cache_peer
      - run:
          name: Install NodeJS Dependencies via YARN
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  test_spec:
    <<: *job_defaults_browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - checkout
      - *restore_yarn_cache
      - *restore_yarn_cache_peer
      - run:
          name: Test Spec
          command: yarn test
  lint:
    <<: *job_defaults
    steps:
      - checkout
      - *restore_yarn_cache
      - *restore_yarn_cache_peer
      - run:
          name: Lint TypeScript
          command: yarn lint

# Workflows
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_spec:
          requires:
            - build
      - lint:
          requires:
            - build
